### ISSUE TITLE
vim totally freezes with log err: Cannot read property 'stdin' of null

### ISSUE THREAD

**Issue by deltaskelta** [mhartington/nvim-typescript#152]
**Warning:  I will close the issue without the minimal vimrc and the reproduce ways.**

# Problems summary

I sometimes get a massive lag and sometimes a freeze in vim when the complete is called through deoplete. When I tried to minimize my init.vim to reproduce the issue it only froze vim completely instead of making it lag. The nvim-node log stops on the error `TypeError: Cannot read property 'stdin' of null`

## Expected

to show the complete menu smoothly

## Environment Information

 * terminal: iterm2
 * vim/nvim version: NVIM v0.3.0

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
all plug#begin('~/.config/nvim/plugged')

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'mhartington/nvim-typescript', { 'do': './install.sh', 'for': ['typescript', 'typescript.jsx']}

call plug#end()

let g:python_host_prog = '/Users/Jeff/.virtualenvs/neovim2/bin/python'
let g:python3_host_prog = '/Users/Jeff/.virtualenvs/neovim/bin/python'
let g:node_host_prog = '/usr/local/bin/neovim-node-host'
let g:ruby_host_prog = '/usr/local/bin/neovim-ruby-host'
let $NVIM_NODE_LOG_FILE='/tmp/nvim-node.log'
let $NVIM_NODE_LOG_LEVEL='info'

let g:deoplete#enable_at_startup = 1

augroup typescript
    autocmd!
    " setting typescript things.
    let g:nvim_typescript#type_info_on_hold = 1
    let g:nvim_typescript#signature_complete = 1

    autocmd BufNewFile,BufRead *.ts set filetype=typescript
    autocmd BufNewFile,BufRead *.tsx set filetype=typescript.jsx
    autocmd FileType typescript set tabstop=2 shiftwidth=2 expandtab
    nnoremap <leader>i :TSImport<CR>
    nnoremap <leader>d :TSDefPreview<CR>
    nnoremap <leader>t :TSType<CR>
    nnoremap <leader>f :TSGetCodeFix<CR> " this is called on insert leave
augroup END

```

## The reproduce ways from neovim starting

NOTE: I have not been able to reproduce this on an example repo yet, it only happens on a production repo that contains a mixture of ts(x) and js(x), I am working on a full reproduction.

## Example project repo?

Most common errors are related to a project not being set up correctly.
Please provid a minimal project example to reduce back-and-forth time.
This makes debugging MUCH easier

## Screen shot (if possible)

tail deoplete.log
```
2018-07-11 21:23:23,407 DEBUG    [16997] (deoplete.child) main_loop: on_event begin
2018-07-11 21:23:24,814 DEBUG    [16994] (deoplete.child) main_loop: end
2018-07-11 21:23:24,814 DEBUG    [16995] (deoplete.child) on_event: Source: omni
2018-07-11 21:23:24,814 DEBUG    [16996] (deoplete.child) on_event: Source: member
2018-07-11 21:23:24,814 DEBUG    [16995] (deoplete.child) on_event: Source: buffer
2018-07-11 21:23:24,814 DEBUG    [16997] (deoplete.child) on_event: Source: around
2018-07-11 21:23:24,814 DEBUG    [16996] (deoplete.child) main_loop: end
2018-07-11 21:23:24,815 DEBUG    [16997] (deoplete.child) on_event: Source: tag
2018-07-11 21:23:24,815 DEBUG    [16997] (deoplete.child) main_loop: end
2018-07-11 21:23:24,821 DEBUG    [16995] (deoplete.child) main_loop: end
```

tail nvim-log
```
2018-07-11T12:26:42.122Z - info: [object Object] object
2018-07-11T12:26:42.122Z - info: Method name getCommonData
2018-07-11T12:26:42.122Z - info: getCommonData() {
        return __awaiter(this, void 0, void 0, function* () {
            let file = yield this.getCurrentFile();
            let cursorPos = yield this.getCursorPos();
            return {
                file,
                line: cursorPos[0],
                offset: cursorPos[1] + 1
            };
        });
    } function
2018-07-11T12:26:42.122Z - info: [object Object] object
2018-07-11T12:26:42.138Z - info: Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'stdin' of null
    at Client._makeTssRequest (/Users/Jeff/.config/nvim/plugged/nvim-typescript/rplugin/node/nvim_typescript/lib/client.js:165:27)
    at Client.updateFile (/Users/Jeff/.config/nvim/plugged/nvim-typescript/rplugin/node/nvim_typescript/lib/client.js:100:21)
    at Object.<anonymous> (/Users/Jeff/.config/nvim/plugged/nvim-typescript/rplugin/node/nvim_typescript/lib/index.js:642:22)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/Jeff/.config/nvim/plugged/nvim-typescript/rplugin/node/nvim_typescript/lib/index.js:13:58)
    at process._tickCallback (internal/process/next_tick.js:68:7) } reason:
```

**Comment by deltaskelta** [comment]
After reading the readme, I can see that this error is caused by not having a typescript syntax file enabled because I had disabled my `leafgarland/typescript-vim` plugin. Maybe we should add a note to the readme that says it will freeze vim?

Is this the behavior you would expect if there is no syntax file?
You recommend yats in the readme, could using `typescript-vim` be the cause of the lagginess that I was mentioning?

**Comment by mhartington** [comment]
Pr's are more than welcomed! Feel free to send one to update the readme.
