### ISSUE TITLE
`Command failed: node_modules/.bin/tsc --version`

### ISSUE THREAD

**Issue by mikew** [mhartington/nvim-typescript#218]
# Problems summary
nvim-typescript doesn't start.

## Expected
nvim-typescript to start.

## Environment Information

 * terminal: gnome-terminal
 * vim/nvim version: NVIM v0.4.0-263-g969cc5599

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
let g:deoplete#enable_at_startup = 1

let $NVIM_PYTHON_LOG_FILE='/tmp/nvim-python.log'
let $NVIM_PYTHON_LOG_LEVEL='debug'
let $NVIM_NODE_LOG_FILE='/tmp/nvim-node.log'
let $NVIM_NODE_LOG_LEVEL='debug'

call plug#begin('~/.cache/vim-plug')
  " REQUIRED: Add a syntax file. YATS is the best
  Plug 'HerringtonDarkholme/yats.vim'
  Plug 'mhartington/nvim-typescript', {'do': './install.sh'}
  " For async completion
  Plug 'Shougo/deoplete.nvim'
  " For Denite features
  Plug 'Shougo/denite.nvim'
call plug#end()
```

## The reproduce ways from neovim starting

1. launch nvim
2. `PlugInstall` and `UpdateRemotePlugins`
3. open this very project

I can see in `/tmp/nvim-node.log` a very big error:

```
2019-02-16T20:14:03.200Z - debug: FILE /home/mike/.cache/vim-plug/nvim-typescript/rplugin/node/nvim_typescript/src/client.ts
2019-02-16T20:14:03.389Z - error: Error in plugin for function:TSOnBufEnter: Command failed: node_modules/.bin/tsc --version (file: /home/mike/.cache/vim-plug/nvim-typescript/rplugin/node/nvim_typescript, stack: Error: Command failed: node_modules/.bin/tsc --version
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:653:13)
    at Client.setTSConfigVersion (/home/mike/.cache/vim-plug/nvim-typescript/rplugin/node/nvim_typescript/lib/client.js:92:43)
    at Object.<anonymous> (/home/mike/.cache/vim-plug/nvim-typescript/rplugin/node/nvim_typescript/lib/index.js:679:25)
    at Generator.next (<anonymous>)
    at fulfilled (/home/mike/.cache/vim-plug/nvim-typescript/rplugin/node/nvim_typescript/lib/index.js:13:58)
    at process._tickCallback (internal/process/next_tick.js:68:7))
2019-02-16T20:14:03.389Z - debug: request -> neovim.api.nvim_eval
2019-02-16T20:14:03.391Z - info: Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'stdin' of null
      at Client._makeTssRequest (/home/mike/.cache/vim-plug/nvim-typescript/rplugin/node/nvim_typescript/lib/client.js:183:27)
      at Client.updateFile (/home/mike/.cache/vim-plug/nvim-typescript/rplugin/node/nvim_typescript/lib/client.js:118:21)
      at Object.<anonymous> (/home/mike/.cache/vim-plug/nvim-typescript/rplugin/node/nvim_typescript/lib/index.js:717:22)
      at Generator.next (<anonymous>)
      at fulfilled (/home/mike/.cache/vim-plug/nvim-typescript/rplugin/node/nvim_typescript/lib/index.js:13:58)
      at process._tickCallback (internal/process/next_tick.js:68:7) } reason:
2019-02-16T20:14:03.391Z - info: Unhandled Rejection at: Promise {
  <rejected> Error: Error: Command failed: node_modules/.bin/tsc --version
      at NvimPlugin.<anonymous> (/usr/local/lib/node_modules/neovim/lib/host/NvimPlugin.js:159:27)
      at Generator.throw (<anonymous>)
      at rejected (/usr/local/lib/node_modules/neovim/lib/host/NvimPlugin.js:5:65)
      at process._tickCallback (internal/process/next_tick.js:68:7) } reason: message=Error: Command failed: node_modules/.bin/tsc --version, stack=Error: Error: Command failed: node_modules/.bin/tsc --version
    at NvimPlugin.<anonymous> (/usr/local/lib/node_modules/neovim/lib/host/NvimPlugin.js:159:27)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/neovim/lib/host/NvimPlugin.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Running `node_modules/.bin/tsc --version`, from nvim, gives expected results:

```
:!node_modules/.bin/tsc --version                                                                                            
Version 3.2.2

Press ENTER or type command to continue
```

and better yet, `checkhealth` says everything works:

```

health#nvim_typescript#check
========================================================================
## Find Node
  - OK: node is in $PATH

## Find Local Typescript
  - OK: local tsserver is found

## Find Global Typescript
  - OK: No global server found but local server found

## Check for node bindings
  - OK: node bindings found

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Python3.5+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='5401'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python version: 2.7.15
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.6.7
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v10.15.1
  - INFO: Neovim node.js host: /usr/local/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.2.1
```

**Comment by mhartington** [comment]
Hi there! Is this still and issue in the latest release?

**Comment by mikew** [comment]
TBH I gave up on getting language server with Vim working and went back to VS Code.
