### ISSUE TITLE
Error when editing a ts file

### ISSUE THREAD

**Issue by TxHawks** [mhartington/nvim-typescript#40]
When editing a `.ts` file I get the error stack at the end of the issue.
The working directory has a `tsconfig.json` file, and I am editing a file from `which tsc` yields `/home/txh/.nvm/versions/node/v6.5.0/bin/tsc`.

(possibly) Relevant parts of init.vim:
```viml
 Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
 Plug 'mhartington/deoplete-typescript', {'for': ['typescript']}
 Plug 'ternjs/tern_for_vim', { 'do': 'npm install', 'for': ['javascript'] }
 Plug 'carlitux/deoplete-ternjs', {'for': ['javascript']}
 Plug 'othree/jspc.vim', {'for': ['javascript']}
 Plug 'pangloss/vim-javascript'
 Plug 'HerringtonDarkholme/yats.vim'

" Enable deoplete on startup
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_smart_case = 1

if !exists('g:deoplete#omni#input_patterns')
  let g:deoplete#omni#input_patterns = {}
endif

if !exists('g:deoplete#omni#functions')
  let g:deoplete#omni#functions = {}
endif

if !exists('g:deoplete#sources')
  let g:deoplete#sources = {}
endif

" Close the documentation window when completion is done
autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif

augroup omni_complete
  " clear commands before resetting
  autocmd!

  " Enable omnicomplete for supported filetypes
  autocmd FileType css,scss setlocal omnifunc=csscomplete#CompleteCSS
  autocmd FileType html,htm.twig,twig,markdown setlocal omnifunc=emmet#CompleteTags
  autocmd FileType javascript setlocal omnifunc=jspc#omni
  autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
  autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags
augroup END

let g:deoplete#omni#functions.javascript = [
  \ 'tern#Complete',
  \ 'jspc#omni'
\]

" Disable deoplete when multiple cursors are used
function! g:Multiple_cursors_before()
  let g:deoplete#disable_auto_complete = 1
endfunction

" Reenable deoplete after multiple cursors are used
function! g:Multiple_cursors_after()
  let g:deoplete#disable_auto_complete = 0
endfunction

let g:deoplete#sources['javascript'] = ['file', 'ternjs', 'ultisnips', 'omni']
let g:deoplete#sources['css\|scss'] = ['file', 'ultisnips', 'omni', 'tag']
```
Any advice would be greatly appreciated.
 
**Error stack:**
```viml
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/txh/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 110, in gather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/home/txh/.config/nvim/plugged/deoplete-typescript/rplugin/python3/deoplete/sources/typescript.py", line 82, in gather_candidates
[deoplete]     self.reload()
[deoplete]   File "/home/txh/.config/nvim/plugged/deoplete-typescript/rplugin/python3/deoplete/sources/typescript.py", line 56, in reload
[deoplete] Traceback (most recent call last):
[deoplete]     self._client.reload(filename, tmpfile.name)
[deoplete]   File "/home/txh/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 110, in gather_results
[deoplete]   File "/home/txh/.config/nvim/plugged/deoplete-typescript/rplugin/python3/deoplete/sources/../../nvim-typescript/client.py", line 180, in reload
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]     response = self.send_request("reload", args, True)
[deoplete]   File "/home/txh/.config/nvim/plugged/deoplete-typescript/rplugin/python3/deoplete/sources/typescript.py", line 82, in gather_candidates
[deoplete]   File "/home/txh/.config/nvim/plugged/deoplete-typescript/rplugin/python3/deoplete/sources/../../nvim-typescript/client.py", line 103, in send_request
[deoplete]     self.reload()
[deoplete]     self.__send_data_to_server(request)
[deoplete]   File "/home/txh/.config/nvim/plugged/deoplete-typescript/rplugin/python3/deoplete/sources/typescript.py", line 56, in reload
[deoplete]   File "/home/txh/.config/nvim/plugged/deoplete-typescript/rplugin/python3/deoplete/sources/../../nvim-typescript/client.py", line 68, in __send_data_to_server
[deoplete]     self._client.reload(filename, tmpfile.name)
[deoplete]     Client.__server_handle.stdin.write(json.dumps(data))
[deoplete]   File "/home/txh/.config/nvim/plugged/deoplete-typescript/rplugin/python3/deoplete/sources/../../nvim-typescript/client.py", line 180, in reload
[deoplete] AttributeError: 'NoneType' object has no attribute 'stdin'
[deoplete]     response = self.send_request("reload", args, True)
[deoplete] Could not get completions from: typescript.  Use :messages for error details.
[deoplete]   File "/home/txh/.config/nvim/plugged/deoplete-typescript/rplugin/python3/deoplete/sources/../../nvim-typescript/client.py", line 103, in send_request
[deoplete]     self.__send_data_to_server(request)
[deoplete]   File "/home/txh/.config/nvim/plugged/deoplete-typescript/rplugin/python3/deoplete/sources/../../nvim-typescript/client.py", line 68, in __send_data_to_server
[deoplete]     Client.__server_handle.stdin.write(json.dumps(data))
[deoplete] AttributeError: 'NoneType' object has no attribute 'stdin'
[deoplete] Could not get completions from: typescript.  Use :messages for error details.
```

**Comment by mhartington** [comment]
This looks related to the server portion. Perhaps the project is not configured correctly. Is there an a sample project to look at that could reproduce this? I am unable to in my test projects.

**Comment by TxHawks** [comment]
Thanks for the quick feedback.

The content of the `tsconfig.json` file is:

```js
{
  "compilerOptions": {
    "module": "es6",
    "allowJs": true,
    "target": "ESNext",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "noEmitHelpers": true,
    "importHelpers":true,
    "sourceMap": true
  },
  "exclude": [
    "node_modules"
  ],
  "awesomeTypescriptLoaderOptions": {
    "useBabel": true,
    "useCache": true
  }
}
```

You can download a demo project reproducing the  the exact that cause this [here](http://txh.io/demo-ts-project.tar.gz).

**Comment by TxHawks** [comment]
Sorry to nag, but any ideas?

**Comment by mhartington** [comment]
On vacation, will look when I get off my flight 

Mike Hartington

**Comment by TxHawks** [comment]
Thanks!

**Comment by codemonkey800** [comment]
I'm getting the same error! I think it's because for the Deoplete plugin, the server isn't being started at all so the `Client.__server_handle` property defaults to `None`.

Files in question:
https://github.com/mhartington/nvim-typescript/blob/master/rplugin/python3/nvim-typescript/client.py
https://github.com/mhartington/nvim-typescript/blob/master/rplugin/python3/deoplete/sources/typescript.py

**Comment by timlag1305** [comment]
Interestingly enough, I was able to "fix" this issue by following the "Debugging" section of the README to update my vim config.

**Comment by mhartington** [comment]
Hey just looking at this. 
I can get the sample project to fail, so I'll have to dig into why it's failing.

@timlag1305 what did you do to change this?

**Comment by timlag1305** [comment]
I added the following to my `init.vim`

```vim
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_ignore_case = 1
let g:deoplete#auto_complete_start_length = 0
let g:auto_complete_start_length = 0
let g:deoplete#enable_refresh_always = 1
let g:deoplete#enable_debug = 1
let g:deoplete#enable_profile = 1
call deoplete#enable_logging('DEBUG', 'deoplete.log')
```

**Comment by timlag1305** [comment]
I looked into this more. I found out that I only need the following to prevent the error:

```vim
call deoplete#enable_logging('DEBUG', 'deoplete.log')
```

**Comment by timlag1305** [comment]
I am no longer getting these errors when commenting out the debug statements. Did you update this repository to fix the issue?

**Comment by mhartington** [comment]
I did, i made some changes to how the server starts and when it starts. 
I also made a few more changes just now, please pull down the latest and update.

**Comment by TxHawks** [comment]
@mhartington -
I updated using `PlugUpdate`, but still get the errors.

**Comment by mhartington** [comment]
Provide me with a minimal project and minimal vimrc. I cannot guess at what the issue is.

**Comment by ValentinKlinghammer** [comment]
Sooo... Weird thing. For me, the error went away after I removed the `node_modules` folder. It didn't come back after `npm i`, not sure what was wrong there. I couldn't reproduce it since, so I'm afraid I cannot share any useful code.

It happened with an Ionic 3 project.
