### ISSUE TITLE
Unknown function: TSOnBufEnter

### ISSUE THREAD

**Issue by mastertinner** [mhartington/nvim-typescript#50]
# Problems summary

When opening a `.ts` file, I get the following error:

```txt
Error detected while processing BufEnter Auto commands for "*.ts":
E117: Unknown function: TSOnBufEnter
```

Autocompletion with Deoplete doesn't work (but works for other file types). If I disable `nvim-typescript`, I don't get the error.

## Expected

No errors and working autocompletion.

## Environment Information

* terminal: iTerm2 3.0.15 on macOS 10.12.4 with zsh 5.3.1
* vim/nvim version: nvim 0.2.0
* vim config: https://github.com/mastertinner/dotfiles/tree/master/vim

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
set nocompatible

call plug#begin('~/.local/share/nvim/plugged')

Plug 'leafgarland/typescript-vim', { 'for': 'typescript' }

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'mhartington/deoplete-typescript', { 'do': 'npm install -g typescript', 'for': 'typescript' }
let g:deoplete#enable_at_startup = 1

call plug#end()
```

## The reproduce ways from neovim starting

 1. Open a `.ts` file

**Comment by mhartington** [comment]
Please make sure you have run `UpdateRemotePlugins` after this plugin has been installed.

**Comment by bmalinconico** [comment]
@mhartington this error occurred for me with my update today. After running UpdateRemotePlugins the error changes to:


```
no notification handler registered for "/Users/bmalinconico/dotfiles/.vim/plugged/nvim-typescript/rplugin/python3/nvim-typescript:function:TSOnBufEnter"
Encountered NvimError loading plugin at /Users/bmalinconico/dotfiles/.vim/plugged/nvim-typescript/rplugin/python3/nvim-typescript: b'Key not found'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/neovim/plugin/host.py", line 133, in _load
    self._discover_classes(module, handlers, path)
  File "/usr/local/lib/python3.5/site-packages/neovim/plugin/host.py", line 163, in _discover_classes
    plugin = cls(self._configure_nvim_for(cls))
  File "/Users/bmalinconico/dotfiles/.vim/plugged/nvim-typescript/rplugin/python3/nvim-typescript/__init__.py", line 73, in __init__
    self.serverPath = self.vim.vars["nvim_typescript#server_path"]
  File "/usr/local/lib/python3.5/site-packages/neovim/api/common.py", line 81, in __getitem__
    return self._get(key)
  File "/usr/local/lib/python3.5/site-packages/neovim/api/nvim.py", line 131, in request
    res = self._session.request(name, *args, **kwargs)
neovim.api.nvim.NvimError: b'Key not found'
```

**Comment by bmalinconico** [comment]
As a follow up I see you added a health check function, that is throwing an error too:

```
health#nvim_typescript#check
========================================================================
  - ERROR: Failed to run healthcheck for "nvim_typescript" plugin. Exception:
    Vim(return):no request handler registered for "/Users/bmalinconico/dotfiles/.vim/plugged/nvim-typescript/rplugin/python3/nvim-typescript:function:TSFindConfig"
```

**Comment by mastertinner** [comment]
Thanks for your replies, guys. I did run `:UpdateRemotePlugins` and got the following messages:

```txt
remote/host: python3 host registered plugins ['nvim-typescript', 'deoplete']
remote/host: generated rplugin manifest: /Users/myUser/.local/share/nvim/rplugin.vim
```

But I'm still having the same problem.

**Comment by bmalinconico** [comment]
I was able to get everything working by checkout out 3b71bb975dfef16a40f92aed6656f7d00ec3be68 which means d817c3110b015cded4b9a44af9d0dc26d62b932f is the culprit.

**Comment by mhartington** [comment]
K, as I thought. Let me push a fix

**Comment by mhartington** [comment]
Just pushed a fix, could you pull the latest and try again?

**Comment by bmalinconico** [comment]
That did it for me, thanks for your quick response.

**Comment by mastertinner** [comment]
Same for me. Thanks, @mhartington!
