### ISSUE TITLE
path to tsc not specified resulting in error on neovim startup

### ISSUE THREAD

**Issue by kiyanwang** [mhartington/nvim-typescript#97]
# Problems summary

I've been using nvim-typescript with deoplete for several months now without any issues.  Today I updated a load of my vim plugins, including nvim-typescript, deoplete etc.  An noticed that when I open any ts file up i get the following error: 

```
error caught in async handler '/Users/nadeemshabir/.vim/bundle/nvim-typescript/rplugin/python3/nvim-typescript:function:TSOnBufEnter [[]]'
Traceback (most recent call last):
  File "/Users/nadeemshabir/.vim/bundle/nvim-typescript/rplugin/python3/nvim-typescript/__init__.py", line 609, in on_bufenter
    self.tsstart()
  File "/Users/nadeemshabir/.vim/bundle/nvim-typescript/rplugin/python3/nvim-typescript/__init__.py", line 72, in tsstart
    self._client.setTsConfig()
  File "/Users/nadeemshabir/.vim/bundle/nvim-typescript/rplugin/python3/nvim-typescript/client.py", line 50, in setTsConfig
    rawOutput = subprocess.check_output(['tsc', '--version'])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 604, in check_output
    with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 856, in __init__
    restore_signals, start_new_session)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 1464, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'tsc'
Press ENTER or type command to continue
```

Running`:CheckHealth` passes since `tsserver` is found in the correct location (local `node_modules/.bin/`, but for some reason `tsc` is not and there's no health check for that.

```bash

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: has("nvim") was successful
  - OK: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim_typescript#check
========================================================================
## Find Node
  - OK: node is in $PATH

## Find Local Typescript
  - OK: local tsserver is found

## Find Global Typescript
  - OK: No global server found but local server found

## Check for deoplete
  - OK: Deoplete is found!

## Check for python 3 bindings
  - OK: has("python3") was successful

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION=''
  - INFO: $VTE_VERSION=''
  - INFO: $SSH_TTY=''
```

I found where the plugin references `tsc` (https://github.com/mhartington/nvim-typescript/blob/master/rplugin/python3/nvim-typescript/client.py#L49):

```python
 def setTsConfig(self):
        rawOutput = subprocess.check_output(['tsc', '--version'])
        # formats out to be a list [major, minor, patch]
        [major, minor, patch] = rawOutput.rstrip().decode(
                "utf-8").split(' ').pop().split('.')
        self.tsConfg = {"major": int(major), "minor": int(
            minor), "patch": int(patch)}
```

And modifed it to make the path explicit:

```python
        rawOutput = subprocess.check_output(['node_modules/.bin/tsc', '--version'])
```

This fixes the problem for me.

But I'm concious that I'm not that familiar with the workings of this plugin, I've been using it without any issues until this morning and managed to get past this problem using the hack above. I would really appreciate some guidance on what I can to do to fix this properly?   I don't have typescript installed globally, and would rather not do that because we use `nvm` on a per project basis in order to keep tooling / dependencies set for individual projects.

## Environment Information

 * terminal: iTerm Mac Osx, zsh
 * vim/nvim version:

```
version
NVIM v0.2.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -pipe -Os -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostic
s-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_neovim/neovim/work/build/config -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_neovim/neovim/work/neovim-0.2.1/s
rc -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_neovim/neovim/work/build/sr
c/nvim/auto -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_neovim/neovim/work/build/include
Compiled by macports@sierra.internal.macports.net

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/local/share/nvim"
```

## Provide a minimal vim rc with less than 50 lines (Required!)

My .vimrc file is here: https://github.com/kiyanwang/dotfiles/blob/master/.vimrc 

I use pathogen to install my plugins

**Comment by mhartington** [comment]
Alright, this looks like it's an issue where there's a local install, but not a global install of typescript. should be quick to fix.

**Comment by mhartington** [comment]
I just pushed a fix this for this. Can you update nvim-typescript and test it out.

**Comment by kiyanwang** [comment]
@mhartington I've just updated `nvim-typescript` and can confirm this is now fixed for me.

Thank you very much :)
